on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri, rust-src

    - run: cargo miri test --no-default-features
      env:
        MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-disable-isolation

    - run: cargo miri test --all-features
      env:
        MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-disable-isolation
